//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSKC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public int ManufacturerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> EnteredByUserID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public bool IsActive { get; set; }
        public string Filename { get; set; }
    }
}
