//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSKC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string SKU { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public string Specifications { get; set; }
        public Nullable<decimal> RetailCost { get; set; }
        public Nullable<decimal> MsrpCost { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> WholCost { get; set; }
        public Nullable<decimal> DealerCost { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> Inventory { get; set; }
        public bool IsActive { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> EnteredByUserID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual Product Product11 { get; set; }
        public virtual Product Product3 { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSection ProductSection { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
