CREATE TABLE [dbo].[Order] (
    [OrderID]                INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]             INT           NOT NULL,
    [OrderDate]              DATETIME      CONSTRAINT [DF_Order_OrderDate] DEFAULT (getdate()) NOT NULL,
    [OrderAmount]            MONEY         NOT NULL,
    [Tax]                    MONEY         NULL,
    [ShippingMethod]         VARCHAR (50)  NULL,
    [ShippingAmount]         MONEY         NOT NULL,
    [ShippingCurrency]       VARCHAR (5)   CONSTRAINT [DF_Order_ShippingCurrency] DEFAULT ('USD') NOT NULL,
    [ShippingStreetAddress1] VARCHAR (255) NOT NULL,
    [ShippingStreetAddress2] VARCHAR (255) NULL,
    [ShippingCity]           VARCHAR (50)  NOT NULL,
    [ShippingState]          CHAR (2)      NOT NULL,
    [ShippingPostalCode]     CHAR (5)      NOT NULL,
    [ShippingPOBox]          VARCHAR (50)  NULL,
    [SpecialInstructions]    VARCHAR (255) NULL,
    [PPTransactionID]        VARCHAR (100) NOT NULL,
    [PPParentTransactionID]  VARCHAR (100) NULL,
    [PPPaymentStatus]        VARCHAR (100) NULL,
    [IsFulfilled]            BIT           NULL,
    [FulfilledDate]          SMALLDATETIME NULL,
    [PromoCode]              VARCHAR (10)  NULL,
    [EnteredByUserID]        INT           CONSTRAINT [DF_Order_EnteredByUserID] DEFAULT ((1)) NOT NULL,
    [DateEntered]            SMALLDATETIME CONSTRAINT [DF_Order_DateEntered] DEFAULT (getdate()) NOT NULL,
    [UpdatedByUserID]        INT           NULL,
    [DateUpdated]            SMALLDATETIME NULL,
    [Status]                 INT           CONSTRAINT [DF_Order_Status] DEFAULT ((1)) NOT NULL,
    [PPInvoiceNumber]        VARCHAR (50)  NULL,
    [PPInvoiceID]            VARCHAR (50)  NULL,
    [PPTransactionType]      VARCHAR (50)  NULL,
    CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED ([OrderID] ASC),
    CONSTRAINT [FK_Order_Customer] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customer] ([CustomerID])
);

