CREATE TABLE [dbo].[Product] (
    [ProductID]       INT            IDENTITY (1, 1) NOT NULL,
    [SKU]             VARCHAR (15)   NULL,
    [CategoryID]      INT            NULL,
    [SectionID]       INT            NULL,
    [Name]            VARCHAR (255)  NULL,
    [Description]     VARCHAR (4000) NULL,
    [Features ]       VARCHAR (4000) NULL,
    [Specifications]  VARCHAR (4000) NULL,
    [RetailCost]      MONEY          NULL,
    [MsrpCost]        MONEY          NULL,
    [ShippingCost]    MONEY          NULL,
    [WholCost]        MONEY          NULL,
    [DealerCost]      MONEY          NULL,
    [ManufacturerID]  INT            NULL,
    [ItemNumber]      VARCHAR (50)   NULL,
    [Inventory]       INT            CONSTRAINT [DF__Knives__Inventor__21B6055D] DEFAULT ((0)) NULL,
    [IsActive]        BIT            CONSTRAINT [DF__Knives__IsActive__239E4DCF] DEFAULT ((1)) NOT NULL,
    [IsFeatured]      BIT            CONSTRAINT [DF__Knives__IsFeatur__22AA2996] DEFAULT ((0)) NOT NULL,
    [DateEntered]     SMALLDATETIME  CONSTRAINT [DF__Knives__DateEnte__20C1E124] DEFAULT (getdate()) NULL,
    [EnteredByUserID] INT            NULL,
    [DateUpdated]     SMALLDATETIME  NULL,
    [UpdatedByUserID] INT            NULL,
    [SupplierID]      INT            NULL,
    [Weight]          FLOAT (53)     NULL,
    CONSTRAINT [PK__Knives] PRIMARY KEY CLUSTERED ([ProductID] ASC),
    CONSTRAINT [FK_Product_Manufacturers] FOREIGN KEY ([ManufacturerID]) REFERENCES [dbo].[Manufacturers] ([ManufacturerID]),
    CONSTRAINT [FK_Product_Product] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ProductID]),
    CONSTRAINT [FK_Product_Product1] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ProductID]),
    CONSTRAINT [FK_Product_ProductCategory] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[ProductCategory] ([ProductCategoryID]),
    CONSTRAINT [FK_Product_ProductSection] FOREIGN KEY ([SectionID]) REFERENCES [dbo].[ProductSection] ([ProductSectionID]),
    CONSTRAINT [FK_Product_Supplier] FOREIGN KEY ([SupplierID]) REFERENCES [dbo].[Supplier] ([SupplierID])
);

