CREATE TABLE [dbo].[ProdFile] (
    [SKU]                    VARCHAR (17)   NULL,
    [ShortDescription]       VARCHAR (100)  NULL,
    [UPCCode]                VARCHAR (50)   NULL,
    [WeightNumber]           FLOAT (53)     NULL,
    [Family]                 VARCHAR (255)  NULL,
    [ClassCode]              VARCHAR (8)    NULL,
    [Closeouts]              VARCHAR (5)    NULL,
    [AvailabilityCode]       VARCHAR (5)    NULL,
    [LongDescription]        VARCHAR (4000) NULL,
    [DateAdded]              DATETIME       NULL,
    [BrandCode]              VARCHAR (12)   NULL,
    [SectionCode]            VARCHAR (12)   NULL,
    [Hazardous]              VARCHAR (5)    NULL,
    [ORMD]                   VARCHAR (5)    NULL,
    [Oversize]               VARCHAR (5)    NULL,
    [Restricted]             VARCHAR (5)    NULL,
    [New]                    VARCHAR (5)    NULL,
    [MSRP]                   FLOAT (53)     NULL,
    [Dealer]                 FLOAT (53)     NULL,
    [MAAP]                   FLOAT (53)     NULL,
    [ItemCategory]           VARCHAR (5)    NULL,
    [CountryOfOrigin]        VARCHAR (5)    NULL,
    [ManufacturerPartNumber] VARCHAR (17)   NULL,
    [CompanyCode]            VARCHAR (50)   NULL,
    [SpecialFlag]            VARCHAR (5)    NULL,
    [ImageFlag]              VARCHAR (5)    NULL,
    [ImageModifiedDate]      DATETIME       NULL,
    [VendorApprovalRequired] VARCHAR (5)    NULL
);

